---
include:
- "**/*.rb"
exclude:
- spec/**/*
- test/**/*
- vendor/**/*
- ".bundle/**/*"
require:
  - rails
domains: []
require_paths: []
max_files: 0
reporters:
- rubocop:version=1.20.0
formatter:
  rubocop:
    version: 1.20.0
