local builtin = require('telescope.builtin')
vim.keymap.set('n', '<C-t>', builtin.git_files, {})
vim.keymap.set('n', '<C-p>', builtin.find_files, {})
vim.keymap.set('n', '\\', builtin.live_grep, {})
vim.keymap.set('n', '<leader>b', builtin.buffers, {})
